
import db.q_quiz as db_quiz
from api.register_student import register_student_account
from api.quiz import *
from api.delete_user import delete_account
from api.activate import activate_account
from api.sign_in import sign_in
from utilities.logger import get_logger as log
from utilities.test_data import get_test_data
import pytest

@pytest.mark.quiz
class TestQuiz:
    logger = log()

    @pytest.mark.skip
    def test_api_db_quiz_create(self, setup):
        # get token from response generated by setup fixture
        token = setup.json().get("token")
        # api call to create quiz and get id, override attribute value
        pytest.quiz_id = create_quiz(token).json().get('id')
        assert pytest.quiz_id == db_quiz.get_quiz_record_by_id(pytest.quiz_id)[0].get('id')  # verify
        # presence of created quiz in db


    # Test for endpoint /quizzes, validating key-value pairs in json response object
    def test_api_quiz_get(self, setup):
        self.logger.debug("getting authentication token")
        token = setup.json().get("token")  # get token from response generated by setup fixture
        self.logger.debug("getting list of quizzes/asserting response status code")
        response = get_quizzes(token)
        self.logger.debug("asserting response code")
        assert response.status_code == 200
        self.logger.debug("asserting response time <=500ms")
        assert response.elapsed.total_seconds() <= 0.5
        quiz_list = response.json()
        for quiz in quiz_list:
            self.logger.debug(f"asserting key-values of quiz id = {quiz['id']}")
            assert isinstance(quiz['name'], str), "name value must be string"
            assert isinstance(quiz['questions'], list), "questions value must be list"
            assert isinstance(quiz['totalScore'], int), "totalScore value must be int"
            assert isinstance(quiz['passingPercentage'], int), "passingPercentage value must be int"
            assert isinstance(quiz['showStopperQuestion'], int) or quiz[
                'showStopperQuestion'] is None, "showStopperQuestion value must be int or None"
            assert isinstance(quiz['id'], int), "id value must be int"
            assert isinstance(quiz['createdAt'], str), "createdAt value must be str"
            assert isinstance(quiz['updatedAt'], str), "updatedAt value must be str"


# Test suit for endpoint /sign up, validating allowed values for email in request json object
@pytest.mark.registration_form
class TestRegistrationEmail:
    logger = log()

    # Positive, Allowable characters: Alphanumeric & Special characters
    def test_allowable_chars_alpha_special(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'positive1'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 200

    # Negative, Email field required, can’t be empty
    def test_empty_email_field(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative1'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 420

    # Positive, Max 128 characters (128)
    def test_max_char_128(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'positive2'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 200

    # Negative, Max 128 characters (129)
    def test_max_char_129(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative2'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Negative, White spaces are not allowed (local port)
    def test_local_port_spaces(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative3'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Negative, White spaces are not allowed (domain)
    def test_domain_spaces(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative4'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Known bug
    # Negative, White spaces are not allowed (last part of the domain)
    @pytest.mark.skip
    def test_last_part_domain_spaces(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative5'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Positive, Local port with 64 characters (64)
    def test_local_port_64_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'positive3'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 200

    # Known bug
    # Negative, Local port with 64 characters (65)
    @pytest.mark.skip
    def test_local_port_65_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative6'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Positive, Domain on the right with 63 characters (63)
    def test_domain_right_63_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'positive4'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 200

    # Known bug
    # Negative, Domain on the right with 63 characters (64)
    @pytest.mark.skip
    def test_domain_right_64_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative7'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Positive, characters in the last part of the domain (63)
    def test_domain_last_63_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'positive5'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 200

    # Known bug
    # Negative, 63 characters in the last part of the domain (64)
    @pytest.mark.skip
    def test_domain_last_64_char(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative8'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    # Known bug
    # Negative, should contain top level domain separated by dot
    @pytest.mark.skip
    def test_tld_separated_dot(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative9'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500

    def test_at_sign(self):
        self.logger.debug("sending request to register user and saving response")
        response = register_student_account(get_test_data('api', 'TestRegistrationEmail', 'negative10'))
        self.logger.debug("asserting response status code")
        assert response.status_code == 500


# End-to-end test suit for API
@pytest.mark.e2e
class TestE2E:
    logger = log()

    # Test for student registration, activation and sign in
    def test_e2e_student_regi_activ_sign_in(self, setup):
        # test data will be used to create new student user
        test_data = get_test_data('api', 'TestE2E', 'student_regi_activ_sign_in')
        self.logger.debug("sending request to register student user")
        response = register_student_account(test_data)
        self.logger.debug("asserting status code 200")
        assert response.status_code == 200
        self.logger.debug("activating account")
        activate_account(test_data["email"])
        self.logger.debug("sending request to sign in activated user")
        response = sign_in(test_data["email"], test_data["password"])
        self.logger.debug("asserting status code 200")
        assert response.status_code == 200
        self.logger.debug("deleting user")
        response = delete_account(test_data['email'], setup.json()['token'])
        if response.status_code == 200:
            self.logger.debug("user deleted")
        else:
            self.logger.error(f"user is not deleted, server response code: {response.status_code}, body: {response.json()}")


